### PR TITLE
Add travis configuration

### PR DESCRIPTION
**Pull request by packetmonkey**

### CODE REVIEW

**Comment by bvogel** [comment]
Nice...

**Comment by packetmonkey** [comment]
@bvogel yeah your other PR inspired this :) I figure if we are going to go though the work of cleaning up the specs lets ensure they stay good.

**Comment by bvogel** [comment]
I'll look into rubocop...

**Comment by packetmonkey** [comment]
@bvogel I'll go ahead and merge this into master, we can set up rubocop on a new PR, and then rebase your PR on master so we can continue working towards that merge.

**Pull request merged**
