### PR TITLE
resolves #15 redefine methods without generating warning

### LINKED ISSUE #15: Redefine PDF::Core methods without causing a warning
There are ways in Ruby to override a method without generating a warning. Please consider using one of those approaches to override the methods in PDF::Core. This will avoid the following warnings:

```
../gems/prawn-templates-0.0.5/lib/pdf/core/document_state.rb:4: warning: method redefined; discarding old initialize
../gems/pdf-core-0.7.0/lib/pdf/core/document_state.rb:4: warning: previous definition of initialize was here
../gems/prawn-templates-0.0.5/lib/pdf/core/object_store.rb:4: warning: method redefined; discarding old initialize
../gems/pdf-core-0.7.0/lib/pdf/core/object_store.rb:16: warning: previous definition of initialize was here
../gems/prawn-templates-0.0.5/lib/pdf/core/page.rb:4: warning: method redefined; discarding old initialize
../gems/pdf-core-0.7.0/lib/pdf/core/page.rb:24: warning: previous definition of initialize was here
../gems/prawn-templates-0.0.5/lib/pdf/core/page.rb:43: warning: method redefined; discarding old dimensions
../gems/pdf-core-0.7.0/lib/pdf/core/page.rb:150: warning: previous definition of dimensions was here
```

Here are some strategies:

* ~~remove the method before redefining it~~ (see https://github.com/asciidoctor/asciidoctor-pdf/blob/579029559cb55afea7f5c30ee47cf69cd85913ed/lib/asciidoctor-pdf/prawn-table_ext/cell/text.rb)
* alias the method before redefining it (e.g., `alias :__initialize :initialize`)
  - oddly, this suppresses the warning
* prepend the methods from a module (see https://github.com/asciidoctor/asciidoctor-pdf/blob/579029559cb55afea7f5c30ee47cf69cd85913ed/lib/asciidoctor-pdf/prawn_ext/formatted_text/fragment.rb)

### PR DESCRIPTION
**Pull request by mojavelinux**
I used a double underscore as the prefix for the aliased method. I'm happy to redefine the methods in a different way, such as by removing the original or using prepend.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Actually, removing initialize generates a different warning, so our only other option is prepend.

**Comment by bvogel** [comment]
Hi, does or doesn't this PR resolve the issue, do I understand correctly that as of now you just managed to swap one kind of warning for another? And if it's resolved, could you have a look into the rubocop issues introduced by this PR?

**Comment by mojavelinux** [comment]
I can confirm this pull request resolves the warning.

I've updated the code. Awaiting the new results.

Btw, I had no idea that you didn't need to use symbols with alias. You learn something new every day.

**Comment by mojavelinux** [comment]
The reason it results the warning is because the original method is still accessible (by way of the fact that we alias) so Ruby no longer believes it is being shadowed.

**Comment by mojavelinux** [comment]
Technically, using prepend is more correct...but in this case probably overkill...and we don't really want to change the hierarchy of the core PDF objects.

**Comment by bvogel** [comment]
Is that urgent to be released? I'd cut a release if needed. If not I'll wait until something more substantial comes up.

**Comment by mojavelinux** [comment]
Not super urgent. Just good hygiene. I'd give it some time and if nothing else comes up, then do a release just so it doesn't linger too long.

**Comment by pointlessone** [comment]
@bvogel I'd suggest releasing as often as possible. We tried both timed releases and when "something more substantial comes up". This led to a year without a release. Follow SemVer and everything should be OK.

**Pull request merged**
