### PR TITLE
Media box

### PR DESCRIPTION
**Pull request by wkirby**

### CODE REVIEW

**Comment by pointlessone** [comment]
Could you please bring the PDF to absolute minimum? At the moment it's a bit more complex than it needs to be for the spec.

**Comment by wkirby** [comment]
@pointlessone this PDF is as simple as I’m able to make it and still produce this error. This structure matches that of PDFs produced by some scanners, where an image is embedded in an page with a media box reference.

This is how we end up in the error condition: we get the MediaBox from the parent object, and that is a reference.

If you are able to simplify it, I welcome you to do so.

**Comment by gettalong** [comment]
@pointlessone @wkirby I have created a sample PDF that is as minimal as possible: [page_with_mediabox_reference1.pdf](https://github.com/prawnpdf/prawn-templates/files/3744356/page_with_mediabox_reference1.pdf) - can you check that it works as test file?

**Comment by wkirby** [comment]
Thanks @gettalong I will try your PDF when I get to my desk this morning.

**Comment by bvogel** [comment]
@wkirby Any news?

**Comment by wkirby** [comment]
@bvogel Sorry about that — the provided PDF breaks in a totally unrelated way. I can go down the rabbit hole of fixing that error, too, but I don't know that it should be blocking for this PR.

**Comment by pointlessone** [comment]
@bvogel You can accept it this PR as is.

@wkirby Would you please report the issue you have with Thomas' PDF?

**Pull request merged**
